### ISSUE TITLE
Bug: postToPizzaOvenService has the operationID and summary around the wrong way

### ISSUE THREAD

**Issue by jimbobbennett** [open-sauced/api#545]
### Describe the bug

The `postToPizzaOvenService` method has the following:

```
    operationId: "Bake a repository with the pizza oven microservice",
    summary: "postToPizzaOvenService",
```

This should be the other way around - with the contents of the summary as the operation ID and vice versa.

### Steps to reproduce

1. Check the OpenAPI spec - `swagger.yaml`, line 3952:

  ```
    /v2/bake:
    post:
      operationId: Bake a repository with the pizza oven microservice
      summary: postToPizzaOvenService
  ```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs
