### ISSUE TITLE
Bug: typo in user controller

### ISSUE THREAD

**Issue by jimbobbennett** [open-sauced/api#546]
### Describe the bug

The `operationId` for the `findOneUserByUsername` has a typo:

```
operationId: "findOneUserByUserame",
```

Should be findOneUserByUsername

### Steps to reproduce

1. In the `swagger.yaml`, line 193
  ```
    "/v2/users/{username}":
    get:
      operationId: findOneUserByUserame
      summary: Finds a user by :username
  ```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs
